#!/usr/bin/env bash

set -e

subject="COSMIC policy update"
branch="policy_nobuild"
description="Generated by cosmic-epoch scripts/policy-update.sh. Uses \`${branch}\` branch to avoid package builds as it contains no code changes."

git submodule status | awk '{ print $2 }' | while read repo
do
    git submodule update --recursive "${repo}"
    pushd "${repo}"
    git fetch origin
    git checkout -B "${branch}" origin/master
    git reset --hard

    #TODO: copy issue template?
    mkdir -p .github
    for path in ".github/PULL_REQUEST_TEMPLATE.md" ".github/workflows/require-checklist.yml"
    do
        mkdir -pv "$(dirname "${path}")"
        cp -v "../${path}" "${path}"
        git add "${path}"
    done

    git commit -a -m "${subject}" -m "${description}"
    git push -f -u origin "${branch}"
    pr_url="$(gh pr list --head "${branch}" --state open --json url --jq '.[].url')"
    if [ -n "${pr_url}" ]
    then
        echo "PR already open: ${pr_url}"
    else
        gh pr create \
            --title "${subject}" \
            --body "${description}" \
            --assignee "@me" \
            --reviewer "pop-os/engineering" \
            --reviewer "pop-os/quality-assurance"
    fi
    popd
done
