#!/usr/bin/env bash

set -e

# This should be the _next_ epoch version
version=1.0.5
subject="Epoch ${version} version update"
description="Generated by cosmic-epoch scripts/version-update.sh"

repos=(
    cosmic-edit
    cosmic-files
    cosmic-player
    cosmic-store
    cosmic-term
)

for repo in "${repos[@]}"
do
    git submodule update --recursive "${repo}"
    pushd "${repo}"
    git fetch origin
    git checkout -B epoch-update origin/master
    git reset --hard
    if [ "$(dpkg-parsechangelog --show-field Version)" != "${version}" ]
    then
        dch --newversion "${version}" --distribution noble "${subject}"
    fi
    cargo set-version "${version}"
    cargo update
    git commit -a -m "${subject}" -m "${description}"
    git push -f -u origin epoch-update
    pr_url="$(gh pr list --head epoch-update --state open --json url --jq '.[].url')"
    if [ -n "${pr_url}" ]
    then
        echo "PR already open: ${pr_url}"
    else
        gh pr create \
            --title "${subject}" \
            --body "${description}" \
            --assignee "@me" \
            --reviewer "pop-os/engineering" \
            --reviewer "pop-os/quality-assurance"
    fi
    popd
done
